<a href="https://colab.research.google.com/github/alex-addanki/Experiments/blob/master/Copy_of_Mini_Hackathon_AuthorIdentification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>




# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Problem Statement

The problem is to identify the author of a  book from a given list of possible authors.

## Learning Objectives

At the end of the experiment, you will be able to :

* Preprocess the text
* Write an algorithm to identify author of a given book
* Use NLTK package

## Background 

Author identification is the task of identifying the author of a given text. It can be considered as a typical classification problem, where a set of books with known authors are used for training. The aim is to automatically determine the corresponding author of an anonymous text. 

## Grading = 25 Marks

## Setup Steps

In [0]:
#@title Please enter your registration id to start: (e.g. P181900101) { run: "auto", display-mode: "form" }
Id = "P181902375" #@param {type:"string"}


In [0]:
#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "9618623777" #@param {type:"string"}


In [0]:
#@title Run this cell to complete the setup for this Notebook

from IPython import get_ipython
ipython = get_ipython()
  
notebook="BLR_M1_Mini_Hackathon_AuthorIdentification" #name of the notebook
Answer = "This notebook is graded by mentors on the day of hackathon"
def setup():
#  ipython.magic("sx pip3 install torch")
   ipython.magic("sx wget https://www.dropbox.com/s/9xivz2pox1i83td/AIML_DS_GOOGLENEWS-VECTORS-NEGATIVE-300_STD.bin?dl=1")
   ipython.magic("sx mv AIML_DS_GOOGLENEWS-VECTORS-NEGATIVE-300_STD.bin?dl=1 AIML_DS_GOOGLENEWS-VECTORS-NEGATIVE-300_STD.bin")
   print ("Setup completed successfully")
   return

def submit_notebook():
    
    ipython.magic("notebook -e "+ notebook + ".ipynb")
    
    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword()}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:        
        print(r["err"])
        return None        
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getAnswer() and getComplexity() and getAdditional() and getConcepts():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional, 
              "concepts" : Concepts, "record_id" : submission_id, 
              "answer" : Answer, "id" : Id, "file_hash" : file_hash,
              "notebook" : notebook}

      r = requests.post(url, data = data)
      r = json.loads(r.text)
      print("Your submission is successful.")
      print("Ref Id:", submission_id)
      print("Date of submission: ", r["date"])
      print("Time of submission: ", r["time"])
      print("View your submissions: https://iiith-aiml.talentsprint.com/notebook_submissions")
      print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
      return submission_id
    else: submission_id
    

def getAdditional():
  try:
    if Additional: return Additional      
    else: raise NameError('')
  except NameError:
    print ("Please answer Additional Question")
    return None

def getComplexity():
  try:
    return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None
  
def getConcepts():
  try:
    return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None

def getAnswer():
  try:
    return Answer
  except NameError:
    print ("Please answer Question")
    return None

def getId():
  try: 
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup 
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()
  
else:
  print ("Please complete Id and Password cells before running setup")



Setup completed successfully


### NOTE: Please feel free to use ML libraries such as Sklearn, NLTK etc whereever applicable

## Stage 1: Sentence Level Classification

You can choose any two authors books from the below list 

* Shakespeare
* Austen
* Chesterton 

The books of the authors are mentioned in **Gutenberg Corpus**.

Click on the [link](https://www.nltk.org/book/ch02.html) for reference.

### Downloading the required nltk Packages

In [0]:
import nltk
nltk.download('gutenberg')
nltk.download('punkt')
import nltk, re, pprint
from nltk import word_tokenize

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


### 1 Mark-> a) Access a particular book by the chosen author. Find number of sentences and words (tokens) present in that book: 

Instructions on accessing the Corpus can be found at the following [link](https://www.nltk.org/book/ch02.html)

In [0]:
#####YOUR CODE HERE###############
import nltk
from nltk.corpus import gutenberg
gutenberg.fileids()
nltk.corpus.gutenberg.fileids()
emma = gutenberg.words('austen-emma.txt')

In [0]:
for fileid  in  gutenberg.fileids():
        num_chars = len(gutenberg.raw(fileid))
        num_words = len(gutenberg.words(fileid))
        num_sents = len(gutenberg.sents(fileid))
        num_vocab = len(set(w.lower() for w in gutenberg.words(fileid)))
        print(round(num_chars/num_words), round(num_words/num_sents), round(num_words/num_vocab), fileid)    


5 25 26 austen-emma.txt
5 26 17 austen-persuasion.txt
5 28 22 austen-sense.txt
4 34 79 bible-kjv.txt
5 19 5 blake-poems.txt
4 19 14 bryant-stories.txt
4 18 12 burgess-busterbrown.txt
4 20 13 carroll-alice.txt
5 20 12 chesterton-ball.txt
5 23 11 chesterton-brown.txt
5 18 11 chesterton-thursday.txt
4 21 25 edgeworth-parents.txt
5 26 15 melville-moby_dick.txt
5 52 11 milton-paradise.txt
4 12 9 shakespeare-caesar.txt
4 12 8 shakespeare-hamlet.txt
4 12 7 shakespeare-macbeth.txt
5 36 12 whitman-leaves.txt


#Before moving ahead choose your two authors based on the your team-nbr: <br/>
**1.** <br/>
Team=1,6,11,16,21,26 &nbsp;&nbsp;&nbsp;         Author-A Vs Author-B <br />
Team=2,7,12,17,22,27 &nbsp;&nbsp;&nbsp;         Author-B Vs Author-C <br />
Team=3,8,13,18,23,28 &nbsp;&nbsp;&nbsp;         Author-C Vs Author-D <br />
Team=4,9,14,19,24 &nbsp;&nbsp;&nbsp;         Author-D Vs Author-E <br />
Team=5,10,15,20,25    &nbsp;&nbsp;&nbsp;         Author-E Vs Author-F <br />

**2.** Link for each of the author to be used for your problem: <br />

Author-A &nbsp;&nbsp; G.K.Chesterton <br />

*   Author-A -> Rudyard Kipling ->  [Short Stories Collection](http://www.gutenberg.org/files/2781/2781-0.txt) &nbsp;&nbsp;
*   Author-B -> Anton Chekhov [Short Stories Collection](http://www.gutenberg.org/files/1732/1732-0.txt) &nbsp;&nbsp;
*   Author-C -> Guy De Maupassant [Short Stories Collection](http://www.gutenberg.org/cache/epub/21327/pg21327.txt)&nbsp;&nbsp;
*   Author-D -> O Henry [Short Stories Collection](http://www.gutenberg.org/cache/epub/2141/pg2141.txt) &nbsp;&nbsp;
*   Author-E -> Mark Twain [Short Stories Collection](http://www.gutenberg.org/files/245/245-0.txt)&nbsp;&nbsp;
*   Author-F -> Saki [Short Stories Collection](http://www.gutenberg.org/files/1477/1477-0.txt)&nbsp;&nbsp;

**Downloading raw text from Gutenberg :**
 Hint: Refer section "Electronic Books" in the following  [link](https://www.nltk.org/book/ch03.html) for the instructions.  
 
 
 **Ensure you appropriately split the above text into multiple short stories, which will be your training data - 2 Marks  (Hint: You may use raw.find() and raw.rfind() in the  [link](https://www.nltk.org/book/ch03.html)   to find appropriate index of the start and end location)**

In [0]:
import nltk, re, pprint
from nltk import word_tokenize
from urllib import request
url = "http://www.gutenberg.org/files/1732/1732-0.txt"
url2 = "http://www.gutenberg.org/files/2781/2781-0.txt"
response = request.urlopen(url)
response2 = request.urlopen(url2)
AntonChekhov = response.read().decode('utf8')
RudyardKipling = response2.read().decode('utf8')



In [0]:
print(type(AntonChekhov),len(AntonChekhov))
print(type(RudyardKipling),len(RudyardKipling))


<class 'str'> 376627
<class 'str'> 181434


In [0]:
AntonChekhov[:75]

'\ufeffProject Gutenberg’s The Schoolmistress and Other Stories, by Anton Chekhov'

In [0]:
RudyardKipling[:75]

'\ufeffThe Project Gutenberg EBook of Just So Stories, by Rudyard Kipling\r\n\r\nThis'

In [0]:
print(AntonChekhov.find("THE SHOEMAKER AND THE DEVIL"))
print(AntonChekhov.find("End of the Project Gutenberg EBook"))

1218
357453


In [0]:
AntonChekhov_withoutTOC = AntonChekhov[1255:357453]
print(AntonChekhov_withoutTOC)

In [0]:
print(RudyardKipling.find("THE BUTTERFLY THAT STAMPED"))
print(RudyardKipling.find("End of the Project Gutenberg EBook"))

1114
162310


In [0]:

RudyardKipling_withoutTOC = RudyardKipling[1150:162310]
print(RudyardKipling_withoutTOC)

In [0]:
#print(AntonChekhov.find("THE SHOEMAKER AND THE DEVIL"))
#print(AntonChekhov_withoutTOC.find("THE BET"))
#print(AntonChekhov_withoutTOC[296261:])
print(AntonChekhov_withoutTOC[0:296261])

In [0]:
AntonChekhov_Train = AntonChekhov_withoutTOC[0:296261]
AntonChekhov_Test  = AntonChekhov_withoutTOC[296261:]

In [0]:
print(RudyardKipling_withoutTOC.find("HOW THE ALPHABET WAS MADE"))
#print(AntonChekhov_withoutTOC.find("THE BET"))
#print(RudyardKipling_withoutTOC[84289:])
#print(RudyardKipling_withoutTOC[0:84289])

In [0]:
RudyardKipling_Train = RudyardKipling_withoutTOC[0:84289]
RudyardKipling_Test  = RudyardKipling_withoutTOC[84289:]

In [29]:
type(RudyardKipling_Train)

str

In [128]:
complete_corpora = RudyardKipling_Train

'HOW THE WHALE GOT HIS THROAT\r\n\r\nIN the sea, once upon a time, O my Best Beloved, there was a Whale, and\r\nhe ate fishes. He ate the starfish and the garfish, and the crab and the\r\ndab, and the plaice and the dace, and the skate and his mate, and the\r\nmackereel and the pickereel, and the really truly twirly-whirly eel. All\r\nthe fishes he could find in all the sea he ate with his mouth--so! Till\r\nat last there was only one small fish left in all the sea, and he was a\r\nsmall ‘Stute Fish, and he swam a little behind the Whale’s right ear,\r\nso as to be out of harm’s way. Then the Whale stood up on his tail and\r\nsaid, ‘I’m hungry.’ And the small ‘Stute Fish said in a small ‘stute\r\nvoice, ‘Noble and generous Cetacean, have you ever tasted Man?’\r\n\r\n‘No,’ said the Whale. ‘What is it like?’\r\n\r\n‘Nice,’ said the small ‘Stute Fish. ‘Nice but nubbly.’\r\n\r\n‘Then fetch me some,’ said the Whale, and he made the sea froth up with\r\nhis tail.\r\n\r\n‘One at a time is eno

## Stage 2: Experiment with Handcrafted features representation

**Stylometry: ** is the quantitative study of literary style through computational distant reading methods. It is based on the observation that authors tend to write in relatively consistent, recognizable and unique ways. For example:

Each person has their own unique vocabulary, sometimes rich, sometimes limited. Although a larger vocabulary is usually associated with literary quality, this is not always the case. Ernest Hemingway is famous for using a surprisingly small number of different words in his writing,1 which did not prevent him from winning the Nobel Prize for Literature in 1954.
Some people write in short sentences, while others prefer long blocks of text consisting of many clauses.
No two people use semicolons, em-dashes, and other forms of punctuation in the exact same way.




**You may explore the following ways to analyze the text and generate handcrafted features by searching text in a probing way:**

a) Could  style of punctuation usage help as an handcrafted feature? Both by those who follow punctuations and by those who don't? Interesting [link](https://qwiklit.com/2014/03/05/top-10-authors-who-ignored-the-basic-rules-of-punctuation/) 

b) The same word can sometimes be used in different contexts repeatedly by different authors. Could this fact be converted as a handcrafted feature? [link](https://www.nltk.org/book/ch01.html)

c) The above two are merely examples; As you might have noticed already the NLTK book [link](https://www.nltk.org/book/) offers several methods of analyzing and understanding text. Each of these analyses is in itself capable of being an handcrafted feature. **However for your evaluation a minimal set of useful handcrafted features which is helping you prove a classification of an is sufficient**

d) Could most command words be used to distinguish authors?  Refer "Counting Vocabulary" section of the [link](https://www.nltk.org/book/ch01.html)

e) How about using a count of most frequently used bi-gram, tri-grams and using it to classify an author?

f) How about using the frequency historgram of the most frequently used words across the stories by a given author a useful feature? 

The limit here is endless limited only by your imagination, and of course your accuracy ! :)


### 2 Marks-> a) Identify 10 handcrafted features of the kind described by the  story above
 




In [0]:
#A simple example: 
#If a particular book by Shakespeare, has x unique words, y average sentence lenght then the feature vector for this author would look as follows:

# UniqueWords    AvgSentLenth     Label 
#      x             y              1 

import numpy as np
import nltk
import glob
import os
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import KMeans
from scipy.cluster.vq import whiten
sentence_tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
word_tokenizer = nltk.tokenize.RegexpTokenizer(r'\w+')

tokens = word_tokenize(RudyardKipling_Train)
sentences = sentence_tokenizer.tokenize(RudyardKipling_Train)
type(tokens)
len(tokens)
#tokens[:100]
print(len(sentences))

598


In [97]:
import numpy as np
import nltk
import glob
import os
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import KMeans
from scipy.cluster.vq import whiten
sentence_tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
word_tokenizer = nltk.tokenize.RegexpTokenizer(r'\w+')

# create feature vectors
num_chapters = 12
fvs_lexical = np.zeros((1, 2), np.float64)
fvs_punct = np.zeros((1, 3), np.float64)

fvs_lexical

array([[0., 0.]])

In [0]:
def split_stories(raw,index):
  short_stories=[]
  for i in range(0,len(index) -1):
    short_stories.append( raw[raw.rfind(index[i]):raw.rfind(index[i+1])] )

  return short_stories



url_kipling = "http://www.gutenberg.org/files/2781/2781-0.txt"
response_kipling = request.urlopen(url_kipling)
raw_kipling = response_kipling.read().decode('utf8')
index_kipling=['HOW THE WHALE GOT HIS THROAT',
               'HOW THE CAMEL GOT HIS HUMP',
               'HOW THE RHINOCEROS GOT HIS SKIN',
               'HOW THE LEOPARD GOT HIS SPOTS',
               'THE ELEPHANT’S CHILD',
               'THE SING-SONG OF OLD MAN KANGAROO',
               'THE BEGINNING OF THE ARMADILLOS',
               'HOW THE FIRST LETTER WAS WRITTEN',
               'HOW THE ALPHABET WAS MADE',
               'THE CRAB THAT PLAYED WITH THE SEA',
               'THE CAT THAT WALKED BY HIMSELF',
               'THE BUTTERFLY THAT STAMPED',
               'End of the Project Gutenberg EBook of Just So Stories, by Rudyard Kipling']


url_chekov = "http://www.gutenberg.org/files/1732/1732-0.txt"
response_chekov = request.urlopen(url_chekov)
raw_chekov = response_chekov.read().decode('utf8')
index_chekov=['THE SCHOOLMISTRESS',
              'A NERVOUS BREAKDOWN',
              'MISERY',
              'CHAMPAGNE',
              'AFTER THE THEATRE',
              'A LADY’S STORY',
              'IN EXILE',
              'THE CATTLE-DEALERS',
              'SORROW',
              'ON OFFICIAL DUTY',
              'THE FIRST-CLASS PASSENGER',
              'A TRAGIC ACTOR',
              'A TRANSGRESSION',
              'SMALL FRY',
              'THE REQUIEM',
              'IN THE COACH-HOUSE',
              'PANIC FEARS',
              'THE BET',
              'THE HEAD-GARDENER’S STORY',
              'THE BEAUTIES',
              'THE SHOEMAKER AND THE DEVIL',
              'End of the Project Gutenberg EBook of The Schoolmistress and Other Stories, by Anton Chekhov']


chekov_stories = split_stories(raw_chekov,index_chekov)
rk_stories = split_stories(raw_kipling,index_kipling)

In [131]:
chekov_stories[2]

'MISERY\r\n\r\n“To whom shall I tell my grief?”\r\n\r\nTHE twilight of evening. Big flakes of wet snow are whirling lazily\r\nabout the street lamps, which have just been lighted, and lying in a\r\nthin soft layer on roofs, horses’ backs, shoulders, caps. Iona Potapov,\r\nthe sledge-driver, is all white like a ghost. He sits on the box without\r\nstirring, bent as double as the living body can be bent. If a regular\r\nsnowdrift fell on him it seems as though even then he would not think it\r\nnecessary to shake it off.... His little mare is white and motionless\r\ntoo. Her stillness, the angularity of her lines, and the stick-like\r\nstraightness of her legs make her look like a halfpenny gingerbread\r\nhorse. She is probably lost in thought. Anyone who has been torn away\r\nfrom the plough, from the familiar gray landscapes, and cast into this\r\nslough, full of monstrous lights, of unceasing uproar and hurrying\r\npeople, is bound to think.\r\n\r\nIt is a long time since Iona and his

In [102]:
type(chekov_stories)

list

In [0]:
for e, ch_text in enumerate(chekov_stories[1]):
    # note: the nltk.word_tokenize includes punctuation
    tokens = nltk.word_tokenize(ch_text.lower())
    words = word_tokenizer.tokenize(ch_text.lower())
    sentences = sentence_tokenizer.tokenize(ch_text)
    vocab = set(words)
    words_per_sentence = np.array([len(word_tokenizer.tokenize(s))
                                   for s in sentences])
    print(sentences)
    

In [92]:
for i in range(0, 21):
    var1='Story'+ str(i) + '.txt'
    with open(var1, 'wb') as fp:
      pickle.dump(chekov_stories[i], fp)
print('end of loop',var1)

end of loop Story20.txt


In [0]:
import numpy as np
import pandas as pd
import os

import lightgbm as lgb
from sklearn.naive_bayes import MultinomialNB

from tqdm import tqdm
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, log_loss
from sklearn.model_selection import KFold

tqdm.pandas()

In [0]:
author, story = [], []
for line in chekov_stories:
    content = line.split()
    author.append('chekov')
    story.append(" ".join(content[1:]))


In [0]:
story

In [0]:
from sklearn import model_selection, preprocessing, linear_model, naive_bayes, metrics, svm
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn import decomposition, ensemble

import pandas, xgboost, numpy, textblob, string
from keras.preprocessing import text, sequence
from keras import layers, models, optimizers
# create a dataframe using texts and lables
trainDF = pandas.DataFrame()
trainDF['author'] = author
trainDF['story'] = story
trainDF

In [0]:
author, story = [], []
for line in rk_stories:
    content = line.split()
    author.append('rk')
    story.append(" ".join(content[1:]))
    
# create a dataframe using texts and lables
trainDF1 = pandas.DataFrame()
trainDF1['author'] = author
trainDF1['story'] = story
trainDF1

In [0]:
authors_corpus = pd.concat([trainDF, trainDF1])
authors_corpus

In [0]:
# split the dataset into training and validation datasets 
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(authors_corpus['story'], authors_corpus['author'])

# label encode the target variable 
encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)
valid_y = encoder.fit_transform(valid_y)

In [158]:
len(train_x)

24

In [0]:
#@title
import numpy as np
import re
import nltk
import glob
import os
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import KMeans
from scipy.cluster.vq import whiten
sentence_tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
word_tokenizer = nltk.tokenize.RegexpTokenizer(r'\w+')
 
# Load data
data_folder = r""
files = sorted(glob.glob(os.path.join(data_folder, "Story*.txt")))
chapters = []
for fn in files:
    with open(fn) as f:
        chapters.append(f.read())
    print(fn)
all_text = ' '.join(chapters)

In [164]:
# create feature vectors
num_chapters = len(train_x)
fvs_lexical = np.zeros((len(train_x), 3), np.float64)
fvs_punct = np.zeros((len(train_x), 3), np.float64)
for e, ch_text in enumerate(train_x):
    # note: the nltk.word_tokenize includes punctuation
    tokens = nltk.word_tokenize(ch_text.lower())
    words = word_tokenizer.tokenize(ch_text.lower())
    sentences = sentence_tokenizer.tokenize(ch_text)
    vocab = set(words)
    words_per_sentence = np.array([len(word_tokenizer.tokenize(s))
                                   for s in sentences])
 
    # average number of words per sentence
    fvs_lexical[e, 0] = words_per_sentence.mean()
    # sentence length variation
    fvs_lexical[e, 1] = words_per_sentence.std()
    # Lexical diversity
    if len(words) > 0 :
      fvs_lexical[e, 2] = len(vocab) / float(len(words))
    else :
      fvs_lexical[e, 2] = 0
    if len(sentences) > 0 :
      fvs_punct[e, 0] = tokens.count(',') / float(len(sentences))
      # Semicolons per sentence
      fvs_punct[e, 1] = tokens.count(';') / float(len(sentences))
      # Colons per sentence
      fvs_punct[e, 2] = tokens.count(':') / float(len(sentences))
    else :
      fvs_punct[e, 0] = 0
      # Semicolons per sentence
      fvs_punct[e, 1] = 0
      # Colons per sentence
      fvs_punct[e, 2] = 0

      
      
# apply whitening to decorrelate the features
print(fvs_lexical,fvs_punct)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: Mean of empty slice.
  
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:110: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


[[23.57317073 13.27755348  0.37403001]
 [22.5049505  15.58599509  0.34095908]
 [18.8028169  12.08260269  0.39625468]
 [20.84656085 17.42687675  0.24365482]
 [35.         26.41240967  0.22380952]
 [33.2970297  24.77044892  0.29438002]
 [15.3        10.0389954   0.32212885]
 [26.26470588 13.94170389  0.33482643]
 [31.19444444 20.08291071  0.29118433]
 [28.68217054 25.37745581  0.18891892]
 [26.17254902 23.65606566  0.21651184]
 [23.35294118 17.53482831  0.21858382]
 [        nan         nan  0.        ]
 [19.78787879 14.37769418  0.22358346]
 [19.04201681 12.44037542  0.32877317]
 [20.39170507 15.91563372  0.2080226 ]
 [23.175      18.53450049  0.18985976]
 [38.56603774 35.47893844  0.15533268]
 [32.26470588 31.98097672  0.349134  ]
 [17.31578947 12.21863388  0.38525836]
 [17.76470588 13.24962187  0.34381898]
 [23.30645161 18.95332868  0.23892734]
 [19.7254902  14.04904355  0.35536779]
 [23.8        21.98817864  0.31344538]] [[1.68292683 0.13414634 0.09756098]
 [1.47524752 0.14851485 0.0

###  5 Marks-> b) Write functions for generated 8 of the above 10 features you described

In [0]:
def

## Stage 3: Experiment with text processing and representation:
TFIDF or CountVectorizer or Word2vec features 


In [0]:
# create a count vectorizer object 
count_vect = CountVectorizer(analyzer='word', token_pattern=r'\w{1,}')
count_vect.fit(trainDF['story'])

# transform the training and validation data using count vectorizer object
xtrain_count =  count_vect.transform(train_x)
xvalid_count =  count_vect.transform(valid_x)

print(xtrain_count,xvalid_count)

In [0]:
# word level tf-idf
tfidf_vect = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', max_features=5000)
tfidf_vect.fit(trainDF['story'])
xtrain_tfidf =  tfidf_vect.transform(train_x)
xvalid_tfidf =  tfidf_vect.transform(valid_x)

print('# word level tf-idf',xtrain_tfidf,xvalid_tfidf)

# ngram level tf-idf 
tfidf_vect_ngram = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', ngram_range=(2,3), max_features=5000)
tfidf_vect_ngram.fit(trainDF['story'])
xtrain_tfidf_ngram =  tfidf_vect_ngram.transform(train_x)
xvalid_tfidf_ngram =  tfidf_vect_ngram.transform(valid_x)

print('# ngram level tf-idf ',xtrain_tfidf_ngram,xvalid_tfidf_ngram)

# characters level tf-idf
tfidf_vect_ngram_chars = TfidfVectorizer(analyzer='char', token_pattern=r'\w{1,}', ngram_range=(2,3), max_features=5000)
tfidf_vect_ngram_chars.fit(trainDF['story'])
xtrain_tfidf_ngram_chars =  tfidf_vect_ngram_chars.transform(train_x) 
xvalid_tfidf_ngram_chars =  tfidf_vect_ngram_chars.transform(valid_x) 

print('# characters level tf-idf ',xtrain_tfidf_ngram_chars,xvalid_tfidf_ngram_chars)


### 3 Marks->  a) Performing basic cleanup operations such as removing the newline characters and removing trailing spaces
For example: If you text looks as follows \[' This is a sentence\n\r. Another sentence \n'], after newline removal your sentence would look like \['This is sentence a . Another sentence'] . In order to do this you can try using a combination of split() and join()

In [0]:
##################### YOUR CODE HERE ##################################


# Clean text
punctuation = ['.', '..', '...', ',', ':', ';', '-', '*', '"', '!', '?']
def clean_text(x):
    x.lower()
    for p in punctuation:
        x.replace(p, '')
    return x

train_x['story_cleaned'] = train_x['story'].apply(lambda x: clean_text(x))
#valid_x['story_cleaned'] = valid_x['text'].apply(lambda x: clean_text(x))


In [0]:
#df=authors_corpus
authors_corpus['story'] = authors_corpus['story'].str.strip(r'\\r')
authors_corpus['story'] = authors_corpus['story'].str.strip(r'\\n')

  
  

In [0]:
authors_corpus=authors_corpus.drop('text_cleaned', axis=1)

In [0]:
classes = {
    'chekov': 0,
    'rk': 1
}

authors_corpus['author'] = authors_corpus['author'].apply(lambda x: classes[x])


In [0]:
authors_corpus

In [0]:


from sklearn.model_selection import train_test_split

train, test = train_test_split(authors_corpus, test_size=0.2)


In [0]:
# Clean text
punctuation = ['.', '..', '...', ',', ':', ';', '-', '*', '"', '!', '?']
def clean_text(x):
    x.lower()
    for p in punctuation:
        x.replace(p, '')
    return x

train['text_cleaned'] = train['story'].apply(lambda x: clean_text(x))
test['text_cleaned'] = test['story'].apply(lambda x: clean_text(x))

In [0]:
train

In [0]:
# Count Vectorizer
cvect = CountVectorizer(ngram_range=(1, 3), stop_words='english')
cvect.fit(pd.concat((train['text_cleaned'], test['text_cleaned']), axis=0))
cvect_train = cvect.transform(train['text_cleaned'])
cvect_test = cvect.transform(test['text_cleaned'])

# TFIDF
tfidf = TfidfVectorizer(ngram_range=(1, 1), stop_words='english')
tfidf.fit(pd.concat((train['text_cleaned'], test['text_cleaned']), axis=0))
tfidf_train = tfidf.transform(train['text_cleaned'])
tfidf_test = tfidf.transform(test['text_cleaned'])

In [0]:
# split the dataset into training and validation datasets 
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(authors_corpus['story'], authors_corpus['author'])

# label encode the target variable 
encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)
valid_y = encoder.fit_transform(valid_y)

### 3 Marks-> b) Tokenize the sentence
**Example of a tokenized sentence:** <br/>Using same example from the previous cell, after tokenization the sentence <br/> \['This is sentence a . Another sentence']  would now be split into two sentences i.e. two elements in the list as follows:  \['This is a sentence .' , ' Another sentence']  
<br/>
You may further choose to break sentences to individual words **if needed. **<br/>
**Example of sentences as list of words:**<br/>
**Before:** ['This is a sentence .' , ' Another sentence']<br/>
**After:** ['This', 'is' ,'a', 'sentence' , ' . ' , ' Another ', ' sentence ' ]

Hint: Consider using 'List comprehensions', whereby you split the sentence with spaces (using split('')) and populate the resulting output a list comprehension.



###  1 Mark-> c) Is stop word removal necessary in the context of author identification? Your thoughts below?

In [0]:
###### YOUR ANSWER IN TEXT##########
import numpy as np
import pandas as pd
import os

import lightgbm as lgb
from sklearn.naive_bayes import MultinomialNB

from tqdm import tqdm
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, log_loss
from sklearn.model_selection import KFold




###  4 Marks-> c) Construct a labelled dataset of sentences

To create a representation of text, convert it into vectors (numbers).** Use any one ** of the following algorithms for the task :

* Countvectorizer or
* TFIDFVectorizer or 
* Word2Vec 

References Documents: 

1.   [Countvectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html)
2.  [TFIDFVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html)


In [0]:
############################ YOUR CODE HERE###########################

#Define a vectorizer

#fit_transform your data to teh vectorizer

#Convert to numpy array if needed

## 4 Marks-> Stage 4: Classification :
Perform a classification using either features obtained from Step2 or Step3

In [0]:
##############################################YOUR CODE HERE###############################

# Further Ideas for exploration after the hackathon:

**Statistical analysis** of text using NLP, by analysis meaning of sentences, feature based grammars and analyzing structure of sentences! For all of this you can reference www.nltk.org/book

### Please answer the questions below to complete the experiment:

In [0]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = " " #@param ["Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]


In [0]:
#@title If it was very easy, what more you would have liked to have been added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = " " #@param {type:"string"}

In [0]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = " " #@param ["Yes", "No"]

In [0]:
#@title Run this cell to submit your notebook for grading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id =return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")