<a href="https://colab.research.google.com/github/alex-addanki/Experiments/blob/master/LXNumpy-1-07312019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
l1=[1,2,3]

In [0]:
l2=[11,22,12]

In [0]:
#made an list of lists
array1=[l1,l2]

In [0]:
array1

[[1, 2, 3], [11, 22, 12]]

In [0]:
print(type(array1))
print(type(l1))
print(type(l2))

<class 'list'>
<class 'list'>
<class 'list'>


In [0]:
#array of lists
array1 = np.array(l1)

In [0]:
print(array1.shape)
print(type(array1))

(3,)
<class 'numpy.ndarray'>


In [0]:
array1

array([1, 2, 3])

In [0]:
l3=[l1,l2]

In [0]:
array2=np.array(l3)

In [0]:
array2

array([[ 1,  2,  3],
       [11, 22, 12]])

In [0]:
array2.shape

(2, 3)

In [0]:
print(type(l3))
print(type(l1),type(l2))
print(type(array2))
print(array2.dtype)

<class 'list'>
<class 'list'> <class 'list'>
<class 'numpy.ndarray'>
int32


In [0]:
#array of ones
a1= np.ones([2,2])

In [0]:
a1

array([[1., 1.],
       [1., 1.]])

In [0]:
#identity matrix
a2= np.eye(5)

In [0]:
a2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
#an array of startwith,end at and step by
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [0]:
#arrays and scalars

In [0]:
#import __future__ division
5/2

2.5

In [0]:
arr1 = np.array([[1,2,3,4,5],[9,10,11,12,13]])

In [0]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 9, 10, 11, 12, 13]])

In [0]:
arr1 * arr1

array([[  1,   4,   9,  16,  25],
       [ 81, 100, 121, 144, 169]])

In [0]:
arr1 - arr1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [0]:
arr1 / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [4.5, 5. , 5.5, 6. , 6.5]])

In [0]:
arr1 ^ 1

array([[ 0,  3,  2,  5,  4],
       [ 8, 11, 10, 13, 12]], dtype=int32)

In [0]:
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.11111111, 0.1       , 0.09090909, 0.08333333, 0.07692308]])

In [0]:
arr1 ** 2

array([[  1,   4,   9,  16,  25],
       [ 81, 100, 121, 144, 169]], dtype=int32)

In [0]:
### Indexing Arrays

In [0]:
arr2 = np.arange(0,11,1)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr2[2]

2

In [0]:
arr2[1:5]

array([1, 2, 3, 4])

In [0]:
arr2[0:4]

array([0, 1, 2, 3])

In [0]:
arr2[0:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr2[:3]

array([0, 1, 2])

In [0]:
arr2[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [0]:
arr2[:5]

array([0, 1, 2, 3, 4])

In [0]:
arr2[0:2] = 100
arr2

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [0]:
arr2

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [2]:
arr2 = np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
slice1= arr2[0:6]
slice1

array([0, 1, 2, 3, 4, 5])

In [4]:
slice2=arr2[:]
slice2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
slice2[0:2] =77
slice2

array([77, 77,  2,  3,  4,  5,  6,  7,  8,  9])

In [6]:
arr2

array([77, 77,  2,  3,  4,  5,  6,  7,  8,  9])

In [0]:
arr3 = arr2.copy()

In [12]:
arr3

array([77, 77,  2,  3,  4,  5,  6,  7,  8,  9])

In [0]:
arr3[0:1] =777

In [14]:
arr3

array([777,  77,   2,   3,   4,   5,   6,   7,   8,   9])

In [15]:
arr2

array([77, 77,  2,  3,  4,  5,  6,  7,  8,  9])

In [0]:
arr_indx=np.array([[1,2,3],[10,11,12],[20,21,22]])

In [37]:
arr_indx

array([[ 1,  2,  3],
       [10, 11, 12],
       [20, 21, 22]])

In [38]:
print(arr_indx[0])
print(arr_indx[1])
print(arr_indx[2])

[1 2 3]
[10 11 12]
[20 21 22]


In [39]:
print(arr_indx[0][2])
print(arr_indx[1][1])
print(arr_indx[2][2])

3
11
22


In [45]:
arr_indx

array([[ 1,  2,  3],
       [10, 11, 12],
       [20, 21, 22]])

In [58]:
arr_indx[:2,1:]

array([[ 2,  3],
       [11, 12]])

In [60]:
arr_indx[1]

array([10, 11, 12])

In [76]:
ar_0s=np.zeros((10,10))
ar_0s

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
ar_0s_len=ar_0s.shape[1]
ar_0s_len

10

In [69]:
for i in range(ar_0s_len):
  ar_0s[i]=1
ar_0s

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [0]:
for i in range(ar_0s_len):
  ar_0s[i]=i
ar_0s

In [78]:
for i in range(ar_0s_len):
  ar_0s[i][2]=i
ar_0s

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 4., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 5., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 6., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 7., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 8., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0., 0., 0., 0., 0., 0.]])

In [93]:
ar_0s[[1,2]]

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0., 0., 0.]])

In [92]:
for i in range(10):
  print(ar_0s[i,2])

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


In [0]:
#Array Transposition

In [102]:
arr_transpose=np.arange(50).reshape(10,5)
arr_transpose

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [107]:
print(arr_transpose.shape)
print(arr_transpose.T)
print(arr_transpose.T.shape)
arr_transpose_T=arr_transpose.T

(10, 5)
[[ 0  5 10 15 20 25 30 35 40 45]
 [ 1  6 11 16 21 26 31 36 41 46]
 [ 2  7 12 17 22 27 32 37 42 47]
 [ 3  8 13 18 23 28 33 38 43 48]
 [ 4  9 14 19 24 29 34 39 44 49]]
(5, 10)


In [112]:
print('---------------------------------------------------------')
print(np.dot(arr_transpose,arr_transpose_T))
print('---------------------------------------------------------')
print(np.dot(arr_transpose,arr_transpose.T))
print('---------------------------------------------------------')

---------------------------------------------------------
[[   30    80   130   180   230   280   330   380   430   480]
 [   80   255   430   605   780   955  1130  1305  1480  1655]
 [  130   430   730  1030  1330  1630  1930  2230  2530  2830]
 [  180   605  1030  1455  1880  2305  2730  3155  3580  4005]
 [  230   780  1330  1880  2430  2980  3530  4080  4630  5180]
 [  280   955  1630  2305  2980  3655  4330  5005  5680  6355]
 [  330  1130  1930  2730  3530  4330  5130  5930  6730  7530]
 [  380  1305  2230  3155  4080  5005  5930  6855  7780  8705]
 [  430  1480  2530  3580  4630  5680  6730  7780  8830  9880]
 [  480  1655  2830  4005  5180  6355  7530  8705  9880 11055]]
---------------------------------------------------------
[[   30    80   130   180   230   280   330   380   430   480]
 [   80   255   430   605   780   955  1130  1305  1480  1655]
 [  130   430   730  1030  1330  1630  1930  2230  2530  2830]
 [  180   605  1030  1455  1880  2305  2730  3155  3580  4005]
 

In [4]:
arr_3d=np.arange(50).reshape(5,5,2)
arr_3d
# 5, 5by2 matrix

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [6]:
print('---------------------------------------------------------')
print(arr_3d.transpose(0,1,2))
print('---------------------------------------------------------')
print(arr_3d.transpose(1,0,2))
print('---------------------------------------------------------')


---------------------------------------------------------
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]

 [[30 31]
  [32 33]
  [34 35]
  [36 37]
  [38 39]]

 [[40 41]
  [42 43]
  [44 45]
  [46 47]
  [48 49]]]
---------------------------------------------------------
[[[ 0  1]
  [10 11]
  [20 21]
  [30 31]
  [40 41]]

 [[ 2  3]
  [12 13]
  [22 23]
  [32 33]
  [42 43]]

 [[ 4  5]
  [14 15]
  [24 25]
  [34 35]
  [44 45]]

 [[ 6  7]
  [16 17]
  [26 27]
  [36 37]
  [46 47]]

 [[ 8  9]
  [18 19]
  [28 29]
  [38 39]
  [48 49]]]
---------------------------------------------------------
